Error importing BURST due to missing underlying dependency: No module named 'pycocotools'

Eval Config:
USE_PARALLEL         : False                         
NUM_PARALLEL_CORES   : 1                             
BREAK_ON_ERROR       : True                          
RETURN_ON_ERROR      : False                         
LOG_ON_ERROR         : /mnt/d/GithubProject/mcv-c6-2024-team3/Week3/TrackEval/error_log.txt
PRINT_RESULTS        : True                          
PRINT_ONLY_COMBINED  : False                         
PRINT_CONFIG         : True                          
TIME_PROGRESS        : True                          
DISPLAY_LESS_PROGRESS : False                         
OUTPUT_SUMMARY       : True                          
OUTPUT_EMPTY_CLASSES : True                          
OUTPUT_DETAILED      : True                          
PLOT_CURVES          : True                          

MotChallenge2DBox Config:
PRINT_CONFIG         : True                          
GT_FOLDER            : /mnt/d/GithubProject/mcv-c6-2024-team3/Week3/TrackEval/data/gt/mot_challenge/
TRACKERS_FOLDER      : /mnt/d/GithubProject/mcv-c6-2024-team3/Week3/TrackEval/data/trackers/mot_challenge/
OUTPUT_FOLDER        : None                          
TRACKERS_TO_EVAL     : ['PerfectTracker']            
CLASSES_TO_EVAL      : ['pedestrian']                
BENCHMARK            : custom                        
SPLIT_TO_EVAL        : train                         
INPUT_AS_ZIP         : False                         
DO_PREPROC           : False                         
TRACKER_SUB_FOLDER   : data                          
OUTPUT_SUB_FOLDER    :                               
TRACKER_DISPLAY_NAMES : None                          
SEQMAP_FOLDER        : None                          
SEQMAP_FILE          : None                          
SEQ_INFO             : None                          
GT_LOC_FORMAT        : {gt_folder}/{seq}/gt/gt.txt   
SKIP_SPLIT_FOL       : False                         

Identity Config:
METRICS              : ['HOTA', 'Identity']          
THRESHOLD            : 0.5                           
PRINT_CONFIG         : True                          

Evaluating 1 tracker(s) on 1 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, Identity, Count


Evaluating PerfectTracker

Tracker PerfectTracker was unable to be evaluated.
Tracking data contains the following invalid timesteps in seq custom-01: 2369, , 2370, , 2371, , 2372, , 2373, , 2374, , 2375, , 2376, , 2377, , 2378, , 2379, , 2380, , 2381, , 2382, , 2383, , 2384, , 2385, , 2386, , 2387, , 2388, , 2389, , 2390, , 2391, , 2392, , 2393, , 2394, , 2395, , 2396, , 2397, , 2398, , 2399, , 2400, , 2401, , 2402, , 2403, , 2404, , 2405, , 2406, , 2407, , 2408, , 2409, , 2410, , 2411, , 2412, , 2413, , 2414, , 2415, , 2416, , 2417, , 2418, , 2419, , 2420, , 2421, , 2422, 
Traceback (most recent call last):
  File "/mnt/d/GithubProject/mcv-c6-2024-team3/Week3/TrackEval/trackeval/eval.py", line 114, in evaluate
    metric_names)
  File "/mnt/d/GithubProject/mcv-c6-2024-team3/Week3/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/mnt/d/GithubProject/mcv-c6-2024-team3/Week3/TrackEval/trackeval/eval.py", line 218, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq)
  File "/mnt/d/GithubProject/mcv-c6-2024-team3/Week3/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/mnt/d/GithubProject/mcv-c6-2024-team3/Week3/TrackEval/trackeval/datasets/_base_dataset.py", line 93, in get_raw_seq_data
    raw_tracker_data = self._load_raw_file(tracker, seq, is_gt=False)
  File "/mnt/d/GithubProject/mcv-c6-2024-team3/Week3/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 222, in _load_raw_file
    [str(x) + ', ' for x in extra_time_keys]))
trackeval.utils.TrackEvalException: Tracking data contains the following invalid timesteps in seq custom-01: 2369, , 2370, , 2371, , 2372, , 2373, , 2374, , 2375, , 2376, , 2377, , 2378, , 2379, , 2380, , 2381, , 2382, , 2383, , 2384, , 2385, , 2386, , 2387, , 2388, , 2389, , 2390, , 2391, , 2392, , 2393, , 2394, , 2395, , 2396, , 2397, , 2398, , 2399, , 2400, , 2401, , 2402, , 2403, , 2404, , 2405, , 2406, , 2407, , 2408, , 2409, , 2410, , 2411, , 2412, , 2413, , 2414, , 2415, , 2416, , 2417, , 2418, , 2419, , 2420, , 2421, , 2422, 
Traceback (most recent call last):
  File "TrackEval/scripts/run_mot_challenge.py", line 91, in <module>
    evaluator.evaluate(dataset_list, metrics_list)
  File "/mnt/d/GithubProject/mcv-c6-2024-team3/Week3/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/mnt/d/GithubProject/mcv-c6-2024-team3/Week3/TrackEval/trackeval/eval.py", line 207, in evaluate
    raise err
  File "/mnt/d/GithubProject/mcv-c6-2024-team3/Week3/TrackEval/trackeval/eval.py", line 114, in evaluate
    metric_names)
  File "/mnt/d/GithubProject/mcv-c6-2024-team3/Week3/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/mnt/d/GithubProject/mcv-c6-2024-team3/Week3/TrackEval/trackeval/eval.py", line 218, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq)
  File "/mnt/d/GithubProject/mcv-c6-2024-team3/Week3/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/mnt/d/GithubProject/mcv-c6-2024-team3/Week3/TrackEval/trackeval/datasets/_base_dataset.py", line 93, in get_raw_seq_data
    raw_tracker_data = self._load_raw_file(tracker, seq, is_gt=False)
  File "/mnt/d/GithubProject/mcv-c6-2024-team3/Week3/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 222, in _load_raw_file
    [str(x) + ', ' for x in extra_time_keys]))
trackeval.utils.TrackEvalException: Tracking data contains the following invalid timesteps in seq custom-01: 2369, , 2370, , 2371, , 2372, , 2373, , 2374, , 2375, , 2376, , 2377, , 2378, , 2379, , 2380, , 2381, , 2382, , 2383, , 2384, , 2385, , 2386, , 2387, , 2388, , 2389, , 2390, , 2391, , 2392, , 2393, , 2394, , 2395, , 2396, , 2397, , 2398, , 2399, , 2400, , 2401, , 2402, , 2403, , 2404, , 2405, , 2406, , 2407, , 2408, , 2409, , 2410, , 2411, , 2412, , 2413, , 2414, , 2415, , 2416, , 2417, , 2418, , 2419, , 2420, , 2421, , 2422, 
